// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptiPulse.Flags.Infrastructure;

#nullable disable

namespace OptiPulse.Flags.Infrastructure.Migrations
{
    [DbContext(typeof(FlagsDbContext))]
    [Migration("20260817104338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OptiPulse.Flags.Domain.Flag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("KillSwitchEngaged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetingRules")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TargetingRulesJson");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Flags", (string)null);
                });

            modelBuilder.Entity("OptiPulse.Flags.Domain.Flag", b =>
                {
                    b.OwnsOne("OptiPulse.Flags.Domain.Rollout", "Rollout", b1 =>
                        {
                            b1.Property<Guid>("FlagId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("PercentageBasisPoints")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Rollout_PercentageBasisPoints");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Rollout_Salt");

                            b1.HasKey("FlagId");

                            b1.ToTable("Flags");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");
                        });

                    b.Navigation("Rollout");
                });
#pragma warning restore 612, 618
        }
    }
}
