// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptiPulse.Flags.Infrastructure;

#nullable disable

namespace OptiPulse.Flags.Infrastructure.Migrations
{
    [DbContext(typeof(FlagsDbContext))]
    [Migration("20260818090856_AddExperiments")]
    partial class AddExperiments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptiPulse.Flags.Domain.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConversionGoal")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FlagId")
                        .HasColumnType("uuid");

                    b.Property<string>("FlagKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FlagKey");

                    b.ToTable("Experiments", (string)null);
                });

            modelBuilder.Entity("OptiPulse.Flags.Domain.Flag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultOutcome")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("KillSwitchEngaged")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TargetingRules")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TargetingRulesJson");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Flags", (string)null);
                });

            modelBuilder.Entity("OptiPulse.Flags.Domain.Experiment", b =>
                {
                    b.OwnsMany("OptiPulse.Flags.Domain.Variant", "Variants", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ExperimentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<Guid?>("MicroCopyCandidateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("WeightBasisPoints")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ExperimentId");

                            b1.ToTable("ExperimentVariants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExperimentId");
                        });

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("OptiPulse.Flags.Domain.Flag", b =>
                {
                    b.OwnsOne("OptiPulse.Flags.Domain.Rollout", "Rollout", b1 =>
                        {
                            b1.Property<Guid>("FlagId")
                                .HasColumnType("uuid");

                            b1.Property<int>("PercentageBasisPoints")
                                .HasColumnType("integer")
                                .HasColumnName("Rollout_PercentageBasisPoints");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Rollout_Salt");

                            b1.HasKey("FlagId");

                            b1.ToTable("Flags");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");
                        });

                    b.Navigation("Rollout");
                });
#pragma warning restore 612, 618
        }
    }
}
