// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptiPulse.Flags.Infrastructure;

#nullable disable

namespace OptiPulse.Flags.Infrastructure.Migrations
{
    [DbContext(typeof(FlagsDbContext))]
    partial class FlagsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptiPulse.Flags.Domain.Flag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultOutcome")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("KillSwitchEngaged")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TargetingRules")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TargetingRulesJson");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Flags", (string)null);
                });

            modelBuilder.Entity("OptiPulse.Flags.Domain.Flag", b =>
                {
                    b.OwnsOne("OptiPulse.Flags.Domain.Rollout", "Rollout", b1 =>
                        {
                            b1.Property<Guid>("FlagId")
                                .HasColumnType("uuid");

                            b1.Property<int>("PercentageBasisPoints")
                                .HasColumnType("integer")
                                .HasColumnName("Rollout_PercentageBasisPoints");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Rollout_Salt");

                            b1.HasKey("FlagId");

                            b1.ToTable("Flags");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");
                        });

                    b.Navigation("Rollout");
                });
#pragma warning restore 612, 618
        }
    }
}
