// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptiPulse.Audit.Infrastructure;

#nullable disable

namespace OptiPulse.Audit.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260817181030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptiPulse.Audit.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AfterStateJson")
                        .HasColumnType("text")
                        .HasColumnName("AfterState");

                    b.Property<string>("BeforeStateJson")
                        .HasColumnType("text")
                        .HasColumnName("BeforeState");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Actor", "OptiPulse.Audit.Domain.AuditEntry.Actor#ActorReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("Actor_Id");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Actor_DisplayName");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Actor_Role");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("OptiPulse.Audit.Domain.ExposureEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContextKey")
                        .HasColumnType("text");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FlagKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariantKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlagKey");

                    b.HasIndex("Timestamp");

                    b.ToTable("ExposureEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
